"""
Deadline Intelligence subsystem for ResearchConnect AI.

Phase 2.7 establishes deterministic, timezone-aware deadline evidence extraction,
normalization, urgency calculation, milestone resolution, and explainability.
"""
from app.ranking.deadline.extractors import (
    DeadlineEvidenceExtractor,
    parse_raw_date_components,
)
from app.ranking.deadline.intelligence import (
    DEFAULT_APPROACHING_WINDOW_DAYS,
    DEFAULT_CRITICAL_WINDOW_DAYS,
    DEFAULT_MAX_URGENCY_WINDOW_DAYS,
    DEFAULT_URGENT_WINDOW_DAYS,
    MILESTONE_LABELS,
    PRIMARY_MILESTONE_PRECEDENCE,
    DeadlineIntelligence,
)
from app.ranking.deadline.models import (
    CanonicalDeadlineView,
    ConflictState,
    DeadlineAssessment,
    DeadlineEvidence,
    DeadlineEvidenceCollection,
    DeadlineObservation,
    DeadlinePrecision,
    DeadlineProvenance,
    DeadlineRevision,
    DeadlineTemporalStatus,
    DeadlineType,
    DefaultTimezonePolicy,
    ExtractionMethod,
    NormalizationStatus,
    NormalizedDeadline,
    NormalizedDeadlineCollection,
    OpportunityCanonicalView,
    OpportunityDeadlineAssessment,
    RevisionClassification,
    SourceAuthorityTier,
    TimezoneIndicator,
    TimezoneSource,
    UrgencyTier,
)
from app.ranking.deadline.normalizers import (
    AOE_OFFSET,
    AOE_TIMEZONE,
    DeadlineNormalizer,
    parse_numeric_offset,
    parse_time_string,
    resolve_timezone,
)
from app.ranking.deadline.explainability import (
    DeadlineExplainabilityService,
    deadline_explainability_service,
)
from app.ranking.deadline.resolvers import (
    DeadlineConflictResolver,
    are_deadlines_equivalent,
    classify_revision,
    infer_source_authority,
)

__all__ = [
    "AOE_OFFSET",
    "AOE_TIMEZONE",
    "CanonicalDeadlineView",
    "ConflictState",
    "DEFAULT_APPROACHING_WINDOW_DAYS",
    "DEFAULT_CRITICAL_WINDOW_DAYS",
    "DEFAULT_MAX_URGENCY_WINDOW_DAYS",
    "DEFAULT_URGENT_WINDOW_DAYS",
    "DeadlineAssessment",
    "DeadlineConflictResolver",
    "DeadlineEvidence",
    "DeadlineEvidenceCollection",
    "DeadlineEvidenceExtractor",
    "DeadlineExplainabilityService",
    "DeadlineIntelligence",
    "DeadlineNormalizer",
    "DeadlineObservation",
    "DeadlinePrecision",
    "DeadlineProvenance",
    "DeadlineRevision",
    "DeadlineTemporalStatus",
    "DeadlineType",
    "deadline_explainability_service",
    "DefaultTimezonePolicy",
    "ExtractionMethod",
    "MILESTONE_LABELS",
    "NormalizationStatus",
    "NormalizedDeadline",
    "NormalizedDeadlineCollection",
    "OpportunityCanonicalView",
    "OpportunityDeadlineAssessment",
    "PRIMARY_MILESTONE_PRECEDENCE",
    "RevisionClassification",
    "SourceAuthorityTier",
    "TimezoneIndicator",
    "TimezoneSource",
    "UrgencyTier",
    "are_deadlines_equivalent",
    "classify_revision",
    "infer_source_authority",
    "parse_numeric_offset",
    "parse_raw_date_components",
    "parse_time_string",
    "resolve_timezone",
]

