from app.schemas.discovery import (
    ExplanationSchema,
    OpportunityMatchItem,
    OpportunityMatchResponse,
    ProvenanceEvidenceSchema,
    ResearchSearchResponse,
    ResearchSearchResultItem,
    ResearchWorkRead,
    SignalContributionSchema,
    SimilarResearchItem,
    SimilarResearchResponse,
    TopicEvidenceSchema,
)
from app.schemas.opportunity import (
    IngestionRunRead,
    IngestionRunStatus,
    OpportunityFee,
    OpportunityListItem,
    OpportunityListResponse,
    OpportunityRead,
)
from app.schemas.researcher import (
    AcademicStatus,
    CompletenessLevel,
    ExternalIdentifiersSchema,
    InstitutionSummarySchema,
    ProfileCompletenessSchema,
    ResearcherProfileCreate,
    ResearcherProfileRead,
    ResearcherProfileUpdate,
    ResearcherWorkSummarySchema,
)
from app.schemas.researcher_intelligence import (
    ExpertiseClassification,
    ResearcherIntelligenceResponse,
    ResearcherIntelligenceSummarySchema,
    ResearcherInterestItemSchema,
    SupportingWorkReferenceSchema,
)

__all__ = [
    "OpportunityFee",
    "OpportunityListItem",
    "OpportunityListResponse",
    "OpportunityRead",
    "IngestionRunRead",
    "IngestionRunStatus",
    "ResearchWorkRead",
    "SignalContributionSchema",
    "TopicEvidenceSchema",
    "ProvenanceEvidenceSchema",
    "ExplanationSchema",
    "ResearchSearchResultItem",
    "ResearchSearchResponse",
    "SimilarResearchItem",
    "SimilarResearchResponse",
    "OpportunityMatchItem",
    "OpportunityMatchResponse",
    # Phase 3.1 Researcher Profile Schemas
    "AcademicStatus",
    "CompletenessLevel",
    "ExternalIdentifiersSchema",
    "InstitutionSummarySchema",
    "ResearcherWorkSummarySchema",
    "ProfileCompletenessSchema",
    "ResearcherProfileCreate",
    "ResearcherProfileUpdate",
    "ResearcherProfileRead",
    # Phase 3.2 Researcher Intelligence Schemas
    "ExpertiseClassification",
    "SupportingWorkReferenceSchema",
    "ResearcherInterestItemSchema",
    "ResearcherIntelligenceSummarySchema",
    "ResearcherIntelligenceResponse",
]

